"""Bounded GitHub/GitLab read adapters with explicit capability receipts."""

from __future__ import annotations

from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor
from http.client import HTTPException
import hashlib
import re
from pathlib import Path
import time
import threading
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode, urlsplit
from urllib.request import HTTPRedirectHandler, Request, build_opener

from ..canonical import canonical_bytes, digest, loads
from . import CONTRACT
from .bundle import atomic
from .model import ScopeError, identity, inventory, path, policy, require, subject, timestamp

MAX_RESPONSE = 4 * 1024 * 1024


def complete(items=()):
    return {"status": "COMPLETE", "items": list(items), "reasons": []}


def unavailable(reason):
    return {"status": "UNAVAILABLE", "items": [], "reasons": [reason]}


class SafeRedirect(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        require(urlsplit(req.full_url).scheme == urlsplit(newurl).scheme == "https" and
                urlsplit(req.full_url).netloc == urlsplit(newurl).netloc,
                "cross-origin or downgraded redirect refused")
        return super().redirect_request(req, fp, code, msg, headers, newurl)


class HTTPTransport:
    def __init__(self):
        self._local = threading.local()
        self.opener = build_opener(SafeRedirect())

    @property
    def opener(self):
        if not hasattr(self._local, "opener"):
            self._local.opener = build_opener(SafeRedirect())
        return self._local.opener

    @opener.setter
    def opener(self, value):
        self._local.opener = value

    def request(self, method, url, headers, body, timeout):
        # GraphQL queries are the sole permitted POST, generated by this module.
        query = loads(body.decode("utf-8")).get("query", "") if body else ""
        require(method == "GET" or method == "POST" and urlsplit(url).path in ("/graphql", "/api/graphql") and
                isinstance(query, str) and query.startswith("query(") and not re.search(r"\bmutation\b", query),
                "adapter permits read operations only")
        deadline = time.monotonic() + timeout
        try:
            response = self.opener.open(Request(url, data=body, headers=headers, method=method), timeout=timeout)
        except HTTPError as exc:
            response = exc
        except (URLError, TimeoutError, OSError) as exc:
            raise ScopeError("NETWORK_UNAVAILABLE") from exc
        with response:
            chunks, size = [], 0
            # read1 returns available bytes, unlike read(n) which can keep
            # accumulating a slow response while each socket timeout resets.
            while True:
                require(time.monotonic() < deadline, "RESPONSE_TIME_CAP")
                chunk = response.read1(min(65536, MAX_RESPONSE + 1 - size))
                if not chunk:
                    break
                chunks.append(chunk); size += len(chunk)
                require(size <= MAX_RESPONSE, "RESPONSE_BYTE_CAP")
            data = b"".join(chunks)
            return response.code, {k.lower(): v for k, v in response.headers.items()}, data


class Client:
    def __init__(self, provider, endpoint, token=None, *, transport=None, max_requests=100,
                 max_pages=10, seconds=120, cache=None, workers=1):
        require(provider in ("github", "gitlab"), "unsupported provider")
        parsed = urlsplit(endpoint)
        require(parsed.scheme == "https" and parsed.hostname and parsed.username is None and parsed.password is None and not parsed.query
                and not parsed.fragment and not endpoint.endswith("/"), "invalid HTTPS endpoint")
        require(type(max_requests) is int and 1 <= max_requests <= 10000 and type(max_pages) is int and
                1 <= max_pages <= 100 and type(seconds) is int and 1 <= seconds <= 3600, "invalid collection budget")
        require(type(workers) is int and 1 <= workers <= 8, "invalid worker budget")
        self.provider, self.endpoint, self.token = provider, endpoint, token
        self.transport = transport or HTTPTransport()
        self.max_requests, self.max_pages, self.seconds = max_requests, max_pages, seconds
        self.deadline = time.monotonic() + seconds
        self.workers, self._budget_lock = workers, threading.Lock()
        self.receipts, self.telemetry, self.requests = [], [], 0
        self.cache = Path(cache) if cache else None
        self.partition = digest({"provider": provider, "endpoint": endpoint,
                                 "credential": hashlib.sha256((token or "anonymous").encode()).hexdigest()})[7:]

    def get(self, path, params=None, *, query=None):
        require(path.startswith("/") and not path.startswith("//") and ".." not in path, "invalid API path")
        with self._budget_lock:
            require(self.requests < self.max_requests and time.monotonic() < self.deadline, "REQUEST_OR_TIME_CAP")
            self.requests += 1
        base = self.endpoint
        if path == "/graphql" and self.provider == "github" and base.endswith("/api/v3"):
            base = base[:-3]
        url = base + path + ("?" + urlencode(params) if params else "")
        headers = {"Accept": "application/json", "User-Agent": "Devostasis-work/1"}
        if self.provider == "github":
            headers["X-GitHub-Api-Version"] = "2022-11-28"
        if self.token:
            headers["Authorization" if self.provider == "github" else "PRIVATE-TOKEN"] = (
                "Bearer " + self.token if self.provider == "github" else self.token)
        cache_path, cached = None, None
        if self.cache and query is None:
            cache_path = self.cache / self.partition / (digest(url)[7:] + ".json")
            try:
                if cache_path.is_file() and not cache_path.is_symlink() and cache_path.stat().st_size < MAX_RESPONSE * 2:
                    entry = loads(cache_path.read_text(encoding="utf-8"))
                    if entry["digest"] == digest(entry["body"]) and entry["url"] == url:
                        cached = entry
                        headers["If-None-Match"] = entry["etag"]
            except (ValueError, KeyError, TypeError, OSError):
                pass
        method, data = ("GET", None) if query is None else ("POST", canonical_bytes(query))
        if data:
            require(path == "/graphql" and "mutation" not in query["query"], "only built-in read query permitted")
            headers["Content-Type"] = "application/json"
        started = time.monotonic()
        receipt_recorded, telemetry = False, None
        try:
            code, response_headers, raw = self.transport.request(method, url, headers, data,
                                                               max(0.1, min(20, self.deadline - started)))
            telemetry = {"path": path, "status": code, "bytes": len(raw),
                         "elapsed_ms": int((time.monotonic() - started) * 1000)}
            self.telemetry.append(telemetry)
            if code not in (200, 304):
                self.receipts.append({"path": path, "status": code, "body_digest": None})
                receipt_recorded = True
            require(code in (200, 304), f"HTTP_{code}")
            if code == 304:
                require(cached is not None, "CACHE_304_WITHOUT_ADMITTED_BODY")
                body = cached["body"]
            else:
                require(len(raw) <= MAX_RESPONSE, "RESPONSE_BYTE_CAP")
                body = loads(raw.decode("utf-8"))
            self.receipts.append({"path": path, "status": 200, "body_digest": digest(body)})
            receipt_recorded = True
            if cache_path and code == 200 and response_headers.get("etag"):
                try:
                    cache_path.parent.mkdir(parents=True, exist_ok=True)
                    atomic(cache_path, canonical_bytes({"url": url, "etag": response_headers["etag"], "body": body, "digest": digest(body)}))
                except OSError:
                    telemetry["cache_write_failed"] = True
            return body, response_headers
        except (ValueError, UnicodeError, OSError, HTTPException) as exc:
            reason = str(exc) if isinstance(exc, ScopeError) else "RESPONSE_OR_CACHE_UNAVAILABLE"
            if not receipt_recorded:
                self.receipts.append({"path": path, "status": "UNAVAILABLE", "body_digest": None, "reason": reason})
            if telemetry is None:
                self.telemetry.append({"path": path, "status": None, "bytes": 0,
                    "elapsed_ms": int((time.monotonic() - started) * 1000), "reason": reason})
            if isinstance(exc, ScopeError):
                raise
            raise ScopeError("RESPONSE_OR_CACHE_UNAVAILABLE") from exc

    def obj(self, path):
        try:
            body, _ = self.get(path)
            require(isinstance(body, dict), "OBJECT_RESPONSE_REQUIRED")
            return body, None
        except ScopeError as exc:
            return None, str(exc)

    def pages(self, path, params=None, key=None):
        items, seen = [], set()
        declared_total, declared_pages = None, None
        def integer_header(headers, name):
            value = headers.get(name)
            if value is None:
                return None
            require(isinstance(value, str) and 0 < len(value) <= 20 and value.isascii() and value.isdecimal(), "INVALID_PAGINATION_HEADER")
            return int(value)
        for page in range(1, self.max_pages + 1):
            try:
                body, headers = self.get(path, {**(params or {}), "per_page": 100, "page": page})
                entries = body[key] if key else body
                require(isinstance(entries, list) and len(entries) <= 100, "INVALID_LIST_RESPONSE")
                for entry in entries:
                    require(isinstance(entry, dict), "LIST_IDENTITY_MISSING")
                    marker = entry.get("id", entry.get("filename", entry.get("new_path")))
                    require(marker is not None, "LIST_IDENTITY_MISSING")
                    marker = str(marker)
                    require(marker not in seen, "PAGINATION_IDENTITY_SHIFT")
                    seen.add(marker); items.append(entry)
                next_page = headers.get("x-next-page") if self.provider == "gitlab" else 'rel="next"' in headers.get("link", "")
                if self.provider == "gitlab":
                    require("x-next-page" not in headers or isinstance(next_page, str), "INVALID_PAGINATION_HEADER")
                    current = integer_header(headers, "x-page")
                    per_page = integer_header(headers, "x-per-page")
                    total = integer_header(headers, "x-total")
                    pages = integer_header(headers, "x-total-pages")
                    require(current is None or current == page, "PAGINATION_PAGE_MISMATCH")
                    require(per_page is None or per_page == 100, "PAGINATION_PAGE_MISMATCH")
                    require(total is None or declared_total is None or total == declared_total, "PAGINATION_TOTAL_SHIFT")
                    require(pages is None or declared_pages is None or pages == declared_pages, "PAGINATION_TOTAL_SHIFT")
                    if total is not None: declared_total = total
                    if pages is not None: declared_pages = pages
                    require(declared_total is None or len(items) <= declared_total, "PAGINATION_TOTAL_MISMATCH")
                    require(declared_pages is None or page <= max(1, declared_pages), "PAGINATION_PAGE_MISMATCH")
                    require(declared_total is None or declared_pages is None or declared_pages == (declared_total + 99) // 100, "PAGINATION_TOTAL_MISMATCH")
                    if next_page:
                        require(integer_header(headers, "x-next-page") == page + 1 and len(entries) == 100, "PAGINATION_PAGE_MISMATCH")
                        require(declared_total is None or len(items) < declared_total, "PAGINATION_TOTAL_MISMATCH")
                        require(declared_pages is None or page < declared_pages, "PAGINATION_PAGE_MISMATCH")
                    terminal = not next_page and (len(entries) < 100 or "x-next-page" in headers)
                    if terminal:
                        require(declared_total is None or len(items) == declared_total, "PAGINATION_TOTAL_MISMATCH")
                        require(declared_pages is None or page == max(1, declared_pages), "PAGINATION_PAGE_MISMATCH")
                elif key and "total_count" in body:
                    total = body["total_count"]
                    require(type(total) is int and total >= 0, "INVALID_LIST_RESPONSE")
                    require(declared_total is None or total == declared_total, "PAGINATION_TOTAL_SHIFT")
                    declared_total = total
                    require(len(items) <= total, "PAGINATION_TOTAL_MISMATCH")
                # Never follow server-supplied URLs with credentials. Request our own page.
                if not next_page and len(entries) < 100:
                    if key and body.get("total_count", len(items)) > len(items):
                        raise ScopeError("SERVER_RESULT_CAP")
                    return complete(items)
                if self.provider == "gitlab" and "x-next-page" in headers and not next_page:
                    return complete(items)
            except (ScopeError, KeyError, TypeError) as exc:
                return {"status": "PARTIAL" if items else "UNAVAILABLE", "items": items,
                        "reasons": [str(exc) if isinstance(exc, ScopeError) else "INVALID_LIST_RESPONSE"]}
        return {"status": "PARTIAL", "items": items, "reasons": ["PAGE_CAP"]}


def _map(coll, mapper):
    items, reasons = [], list(coll["reasons"])
    for item in coll["items"]:
        try:
            items.append(mapper(item))
        except (ScopeError, KeyError, TypeError, ValueError, AttributeError):
            reasons.append("SOURCE_OBJECT_MALFORMED")
    return {"status": "PARTIAL" if reasons and items else "UNAVAILABLE" if reasons else "COMPLETE",
            "items": items, "reasons": sorted(set(reasons))}


def _owners(value):
    return sorted({a["login"] if "login" in a else a["username"] for a in value.get("assignees", [])})


def _gh_issue(i):
    require(i["state"] in ("open", "closed"), "ISSUE_STATE_UNKNOWN")
    return {"id": str(i["number"]), "title": i["title"], "state": "OPEN" if i["state"] == "open" else "CLOSED",
            "owners": _owners(i), "updated_at": timestamp(i["updated_at"])}


def _gl_issue(i):
    require(i["state"] in ("opened", "closed"), "ISSUE_STATE_UNKNOWN")
    return {"id": str(i["iid"]), "title": i["title"], "state": "OPEN" if i["state"] == "opened" else "CLOSED",
            "owners": _owners(i), "updated_at": timestamp(i["updated_at"])}


def _change_binding(client, raw):
    if client.provider == "github":
        target = (raw.get("base") or {}).get("repo") or {}
        source = (raw.get("head") or {}).get("repo") or {}
        target_id, source_id, locator = target.get("id"), source.get("id"), source.get("full_name")
        head, ref = raw["head"]["sha"], str(raw["number"])
    else:
        target_id, source_id = raw.get("target_project_id"), raw.get("source_project_id")
        locator = str(source_id) if source_id is not None else None
        head, ref = raw["sha"], str(raw["iid"])
    if target_id is None or source_id is None or not locator:
        return {}
    project = {"provider": client.provider, "endpoint": client.endpoint, "project_id": str(target_id)}
    return {"source_binding": {"contract": "devostasis.work-source.v1", "kind": "CHANGE", "project": project,
            "source_project": {**project, "project_id": str(source_id)}, "source_locator": locator,
            "ref": ref, "revision": head}}


def _gh_change(client, repo, num):
    route = f"/repos/{repo}/pulls/{num}"
    p, err = client.obj(route)
    require(p is not None, err or "CHANGE_UNAVAILABLE")
    require(str(p.get("number")) == str(num), "CHANGE_IDENTITY_MISMATCH")
    head = p["head"]["sha"]
    raw_reviews = client.pages(route + "/reviews")
    reviews = _map(raw_reviews, lambda r: {"id": str(r["id"]), "actor": r["user"]["login"],
        "revision": r["commit_id"], "state": r["state"], "at": timestamp(r["submitted_at"])})
    # Pending reviews have no verdict and are not approvals.
    if raw_reviews["status"] == "COMPLETE":
        reviews = _map(complete([r for r in raw_reviews["items"] if r.get("state") != "PENDING"]),
            lambda r: {"id": str(r["id"]), "actor": r["user"]["login"], "revision": r["commit_id"],
                       "state": r["state"], "at": timestamp(r["submitted_at"])})
    runs = client.pages(f"/repos/{repo}/commits/{head}/check-runs", key="check_runs")
    checks = _map(runs, lambda c: {"id": "check:" + str(c["id"]), "name": c["name"], "revision": c["head_sha"],
        "state": "PENDING" if c["status"] != "completed" else "PASS" if c.get("conclusion") == "success" else
        "UNKNOWN" if c.get("conclusion") in (None, "neutral", "skipped") else "FAIL",
        "at": timestamp(c.get("completed_at") or c["started_at"])})
    statuses = _map(client.pages(f"/repos/{repo}/commits/{head}/statuses"), lambda c: {
        "id": "status:" + str(c["id"]), "name": c["context"], "revision": head,
        "state": {"success": "PASS", "failure": "FAIL", "error": "FAIL", "pending": "PENDING"}[c["state"]],
        "at": timestamp(c["updated_at"])})
    checks = {"status": "COMPLETE" if checks["status"] == statuses["status"] == "COMPLETE" else "PARTIAL",
              "items": checks["items"] + statuses["items"], "reasons": sorted(set(checks["reasons"] + statuses["reasons"]))}
    files = _map(client.pages(route + "/files"), lambda f: path(f["filename"]))
    # GitHub's file listing is capped at 3000, independently of page budget.
    if p.get("changed_files") != len(files["items"]):
        files["status"] = "PARTIAL"; files["reasons"] = sorted(set(files["reasons"] + ["FILES_RESULT_CAP"]))
    threads, train = unavailable("GRAPHQL_UNAVAILABLE"), None
    owner, name = repo.split("/")
    cursor, thread_items = None, []
    for _ in range(client.max_pages):
        query = "query($owner:String!,$name:String!,$number:Int!,$cursor:String){repository(owner:$owner,name:$name){pullRequest(number:$number){headRefOid mergeQueueEntry{id} reviewThreads(first:100,after:$cursor){nodes{id isResolved} pageInfo{hasNextPage endCursor}}}}}"
        try:
            body, _ = client.get("/graphql", query={"query": query, "variables": {"owner": owner, "name": name, "number": int(num), "cursor": cursor}})
            require(not body.get("errors"), "GRAPHQL_CAPABILITY_UNAVAILABLE")
            obj = body["data"]["repository"]["pullRequest"]
            require(obj["headRefOid"] == head, "HEAD_CHANGED_DURING_COLLECTION")
            train = obj["mergeQueueEntry"] is not None
            node = obj["reviewThreads"]
            thread_items += [{"id": r["id"], "resolved": r["isResolved"]} for r in node["nodes"]]
            if not node["pageInfo"]["hasNextPage"]:
                threads = complete(thread_items); break
            next_cursor = node["pageInfo"]["endCursor"]
            require(next_cursor and next_cursor != cursor, "GRAPHQL_CURSOR_SHIFT")
            cursor = next_cursor
            threads = {"status": "PARTIAL", "items": thread_items, "reasons": ["PAGE_CAP"]}
        except (ScopeError, KeyError, TypeError) as exc:
            threads = {"status": "PARTIAL" if thread_items else "UNAVAILABLE", "items": thread_items,
                       "reasons": [str(exc) if isinstance(exc, ScopeError) else "GRAPHQL_MALFORMED"]}; break
    final, failure = client.obj(route)
    require(final is None or str(final.get("number")) == str(num), "CHANGE_IDENTITY_MISMATCH")
    if final is None or final.get("head", {}).get("sha") != head or final.get("base", {}).get("sha") != p["base"]["sha"] or final.get("updated_at") != p["updated_at"]:
        reviews = unavailable(failure or "CHANGE_MOVED_DURING_COLLECTION")
        checks = unavailable(failure or "CHANGE_MOVED_DURING_COLLECTION")
        threads = unavailable(failure or "CHANGE_MOVED_DURING_COLLECTION")
    return {**_change_binding(client, p), "id": str(p["number"]), "title": p["title"], "state": "MERGED" if p.get("merged") else "OPEN" if p["state"] == "open" else "CLOSED",
            "author": p["user"]["login"], "owners": _owners(p),
            "reviewers": sorted({r["login"] for r in p.get("requested_reviewers", [])}), "head": head, "base": p["base"]["sha"],
            "updated_at": timestamp(p["updated_at"]), "draft": p.get("draft"),
            "conflict": None if p.get("mergeable") is None else not p["mergeable"], "merge_train": train,
            "reviews": reviews, "checks": checks, "threads": threads, "files": files}


def _gl_change(client, project, num, trains=None):
    route = f"/projects/{project}/merge_requests/{num}"
    p, err = client.obj(route); require(p is not None, err or "CHANGE_UNAVAILABLE")
    require(str(p.get("iid")) == str(num), "CHANGE_IDENTITY_MISMATCH")
    head = p["sha"]
    # GitLab aggregate approval endpoint does not identify the reviewed SHA.
    # Never fabricate exact-head approvals from it; explicit unknown is safe.
    approval, approval_err = client.obj(route + "/approvals")
    reviews = unavailable(approval_err or "GITLAB_EXACT_HEAD_APPROVAL_UNAVAILABLE")
    discussions = client.pages(route + "/discussions")
    def discussion(d):
        notes = [n for n in d["notes"] if n.get("resolvable")]
        return {"id": d["id"], "resolved": all(n.get("resolved") is True for n in notes)}
    threads = _map(discussions, discussion)
    diffs = client.pages(route + "/diffs")
    # Diff records have no native id; use safe path identity in Client.pages.
    files = _map(diffs, lambda d: path(d["new_path"]))
    count = p.get("changes_count")
    if not isinstance(count, str) or not count.isdigit() or int(count) != len(files["items"]):
        files["status"] = "PARTIAL"; files["reasons"] = sorted(set(files["reasons"] + ["FILES_RESULT_CAP_OR_UNKNOWN_COUNT"]))
    if trains is None:
        trains = client.pages(f"/projects/{project}/merge_trains", {"scope": "active"})
    train = None
    if trains["status"] == "COMPLETE":
        try:
            train = any(str(t["merge_request"]["iid"]) == str(num) for t in trains["items"])
        except (KeyError, TypeError):
            pass
    pipes = client.pages(route + "/pipelines")
    checks = complete()
    exact = [v for v in pipes["items"] if v.get("sha") == head]
    if pipes["status"] != "COMPLETE":
        checks = unavailable("PIPELINE_INVENTORY_INCOMPLETE")
    elif exact:
        pipeline = max(exact, key=lambda v: int(v["id"]))
        jobs = client.pages(f"/projects/{project}/pipelines/{pipeline['id']}/jobs", {"include_retried": "true"})
        checks = _map(jobs, lambda j: {"id": str(j["id"]), "name": j["name"], "revision": head,
            "state": "PASS" if j["status"] == "success" else "FAIL" if j["status"] in ("failed", "canceled") else
            "MANUAL" if j["status"] == "manual" else "UNKNOWN" if j["status"] == "skipped" else "PENDING",
            "at": timestamp(j.get("finished_at") or j.get("started_at") or j["created_at"])})
    final, failure = client.obj(route)
    require(final is None or str(final.get("iid")) == str(num), "CHANGE_IDENTITY_MISMATCH")
    if final is None or final.get("sha") != head or final.get("updated_at") != p["updated_at"]:
        checks = unavailable(failure or "CHANGE_MOVED_DURING_COLLECTION")
        threads = unavailable(failure or "CHANGE_MOVED_DURING_COLLECTION")
    return {**_change_binding(client, p), "id": str(p["iid"]), "title": p["title"], "state": {"opened": "OPEN", "merged": "MERGED", "closed": "CLOSED", "locked": "OPEN"}[p["state"]],
            "author": p["author"]["username"], "owners": _owners(p),
            "reviewers": sorted({r["username"] for r in p.get("reviewers", [])}), "head": head,
            "base": p["diff_refs"]["base_sha"], "updated_at": timestamp(p["updated_at"]), "draft": p.get("draft"),
            "conflict": p.get("has_conflicts"), "merge_train": train,
            "reviews": reviews, "checks": checks, "threads": threads, "files": files}


def collect(client, locator, config, at=None, revision=None, context="CANONICAL", selected=None,
            source_ref=None, source_change=None, source_project=None, change_refs=None):
    policy(config)
    require(isinstance(locator, str) and ((locator.isdigit() or re.fullmatch(r"[A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)+", locator)
            and all(v not in (".", "..") for v in locator.split("/"))) if client.provider == "gitlab" else
            re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", locator) and
            all(v not in (".", "..") for v in locator.split("/"))), "invalid project locator")
    project_route = f"/repos/{locator}" if client.provider == "github" else f"/projects/{quote(locator, safe='')}"
    meta, failure = client.obj(project_route)
    require(meta is not None, failure or "PROJECT_IDENTITY_UNAVAILABLE")
    if client.provider == "gitlab":
        locator = str(meta["id"])
        project_route = f"/projects/{locator}"
    branch = meta["default_branch"]
    ref_route = project_route + ("/commits/" if client.provider == "github" else "/repository/commits/") + quote(branch, safe="")
    commit, failure = client.obj(ref_route)
    require(commit is not None, failure or "DEFAULT_REVISION_UNAVAILABLE")
    default_sha = commit["sha"] if client.provider == "github" else commit["id"]
    require(context != "CANONICAL" or revision in (None, default_sha), "canonical context must name current default revision")
    project = {"provider": client.provider, "endpoint": client.endpoint, "project_id": str(meta["id"]),
               "locator": meta["full_name"] if client.provider == "github" else str(meta["id"]),
               "revision": revision or default_sha, "context": context}
    if context == "CANONICAL":
        require(source_ref is None and source_change is None and source_project is None, "canonical source must be default branch")
        project["source_binding"] = {"contract": "devostasis.work-source.v1", "kind": "DEFAULT_BRANCH",
            "project": identity(project), "source_project": identity(project), "source_locator": project["locator"],
            "ref": branch, "revision": default_sha}
    else:
        from .binding import resolve
        require((source_ref is None) != (source_change is None), "candidate requires exactly one named source ref or change")
        bound = resolve(client, project, "CHANGE" if source_change is not None else "BRANCH",
                        source_change or source_ref, source_project)
        require(revision is None or revision == bound["revision"], "candidate revision moved or does not exist in source project")
        project["revision"] = bound["revision"]
        project["source_binding"] = bound
    subject(project)
    change_fn, issue_fn = (_gh_change, _gh_issue) if client.provider == "github" else (_gl_change, _gl_issue)
    change_route = project_route + ("/pulls" if client.provider == "github" else "/merge_requests")
    if selected is not None:
        refs = [selected["source"].split(":", 1)[1]] if selected["source"].startswith("change:") else []
        for criterion in config["criteria"]:
            if selected.get("criterion") == criterion["id"]:
                refs += criterion["implementations"]
        changes = complete()
    elif change_refs is not None:
        require(isinstance(change_refs, list) and len(change_refs) <= 100 and
                all(isinstance(r, str) and r.isdigit() for r in change_refs), "invalid bounded change selection")
        refs = change_refs + [r for c in config["criteria"] for r in c["implementations"]]
        changes = complete()
    else:
        changes = client.pages(change_route, {"state": "open" if client.provider == "github" else "opened", "scope": "all"} if client.provider == "gitlab" else {"state": "open"})
        refs = [str(v["number"] if client.provider == "github" else v["iid"]) for v in changes["items"]]
        refs += [r for c in config["criteria"] for r in c["implementations"]]
    mapped_changes, errors = [], list(changes["reasons"])
    ordered = sorted(set(refs), key=lambda v: int(v))
    trains = client.pages(f"/projects/{locator}/merge_trains", {"scope": "active"}) if client.provider == "gitlab" and ordered else None

    def read_change(ref):
        try:
            return (change_fn(client, locator, ref, trains) if client.provider == "gitlab" else
                    change_fn(client, locator, ref)), None
        except (ScopeError, KeyError, TypeError, ValueError) as exc:
            return None, str(exc) if isinstance(exc, ScopeError) else "CHANGE_MALFORMED"

    with ThreadPoolExecutor(max_workers=client.workers) as pool:
        for change, error in pool.map(read_change, ordered):
            if error:
                errors.append(error)
            else:
                mapped_changes.append(change)
    changes = {"status": "PARTIAL" if errors and mapped_changes else "UNAVAILABLE" if errors else "COMPLETE",
               "items": mapped_changes, "reasons": sorted(set(errors))}
    issues = complete()
    issue_refs = {c["issue"] for c in config["criteria"]} | {d for c in config["criteria"] for d in c["dependencies"]} | {d for r in config["requests"] for d in r["dependencies"]}
    if selected is not None:
        issue_refs = set(selected["dependencies"])
        if selected["source"].startswith("issue:"):
            issue_refs.add(selected["source"].split(":", 1)[1])
    for ref in sorted(issue_refs, key=lambda v: int(v)):
        raw, failure = client.obj(project_route + "/issues/" + quote(ref, safe=""))
        try:
            require(raw is not None and "pull_request" not in raw, failure or "ISSUE_UNAVAILABLE")
            require(str(raw.get("number" if client.provider == "github" else "iid")) == ref, "ISSUE_IDENTITY_MISMATCH")
            issues["items"].append(issue_fn(raw))
        except (ScopeError, KeyError, TypeError, ValueError):
            issues["reasons"] = ["ISSUE_OR_DEPENDENCY_UNAVAILABLE"]
    if issues["reasons"]:
        issues["status"] = "PARTIAL" if issues["items"] else "UNAVAILABLE"
    now = timestamp(at or datetime.now(timezone.utc).isoformat())
    result = {"contract": CONTRACT, "kind": "inventory", "subject": project, "observed_at": now,
              "changes": changes, "issues": issues, "receipts": sorted(client.receipts, key=canonical_bytes),
              "selection": {"changes": "SELECTED" if selected is not None or change_refs is not None else "OPEN_AND_REGISTERED", "issues": sorted(issue_refs)}}
    return inventory(result)
